import { getEventContext } from "@/lib/data";
import { PrintButton } from "@/components/PrintButton";
import { FormattedDate, FormattedTime } from "@/components/FormattedTime";
import type { BlockRow, ShotRow } from "@/lib/types";

export default async function PrintEventPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const { supabase, event, viewerRole, user } = await getEventContext(id);

  const [{ data: blocksData }, { data: shotsData }] = await Promise.all([
    supabase.from("blocks").select("*").eq("event_id", id).order("position"),
    // RLS already scopes this per role (owner sees all, others see their own
    // + shared) — filtered again below so an owner's export doesn't leak
    // other people's private shots into a document meant to be handed out.
    supabase.from("shots").select("*").eq("event_id", id).order("created_at"),
  ]);

  const blocks = (blocksData ?? []) as BlockRow[];
  const shots = (
    viewerRole === "owner"
      ? (shotsData ?? [])
      : (shotsData ?? []).filter(
          (s) => s.created_by === user.id || s.visibility === "shared"
        )
  ) as ShotRow[];

  const shotsByBlock = new Map<string, ShotRow[]>();
  for (const shot of shots) {
    shotsByBlock.set(shot.block_id, [...(shotsByBlock.get(shot.block_id) ?? []), shot]);
  }

  return (
    <div className="min-h-dvh bg-white px-6 py-10 text-black print:p-0">
      <PrintButton />
      <div className="mx-auto max-w-2xl">
        <h1 className="text-[26px] font-bold">{event.title}</h1>
        <p className="mt-1 text-[14px] text-black/60">
          <FormattedDate date={event.date} />
          {event.location ? ` · ${event.location}` : ""}
        </p>
        {event.couple_names ? (
          <p className="mt-0.5 text-[14px] text-black/60">{event.couple_names}</p>
        ) : null}

        <div className="mt-8 space-y-6">
          {blocks.length === 0 ? (
            <p className="text-[14px] text-black/60">No timeline blocks yet.</p>
          ) : (
            blocks.map((block) => {
              const blockShots = shotsByBlock.get(block.id) ?? [];
              return (
                <div key={block.id} className="break-inside-avoid border-t border-black/10 pt-3">
                  <div className="flex items-baseline justify-between gap-3">
                    <h2 className="text-[16px] font-semibold">{block.title}</h2>
                    <span className="shrink-0 font-mono text-[13px] text-black/60">
                      <FormattedTime iso={block.start_time} /> – <FormattedTime iso={block.end_time} />
                    </span>
                  </div>
                  {block.location ? (
                    <p className="mt-0.5 text-[13px] text-black/60">{block.location}</p>
                  ) : null}
                  {block.notes ? (
                    <p className="mt-1 text-[13.5px] leading-relaxed">{block.notes}</p>
                  ) : null}
                  {blockShots.length > 0 && (
                    <ul className="mt-2 space-y-1 pl-4">
                      {blockShots.map((shot) => (
                        <li key={shot.id} className="text-[13px] text-black/80">
                          <span className="font-medium">{shot.title}</span>
                          {shot.description ? ` — ${shot.description}` : ""}
                          <span className="text-black/50"> ({shot.duration_minutes}m)</span>
                        </li>
                      ))}
                    </ul>
                  )}
                </div>
              );
            })
          )}
        </div>

        <p className="mt-10 text-[11px] text-black/40">Generated by Everplan</p>
      </div>
    </div>
  );
}
